name: Auto-merge PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # checkout the PR source branch so we can delete it after merge
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      # if a PR is from this repository (not a fork), enable automerge
      - name: Enable automerge
        if: github.event.pull_request.head.repo.full_name == github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge --auto --squash --delete-branch "$PR_URL"
        shell: bash